name: "Run Shell Commands Concurrently"
description: "Run shell commands concurrently"

inputs:
  commands:
    description: "List of commands to run concurrently. format: [{shell: 'bash', commands: ['echo a', 'echo b', 'echo c']}, {shell: 'bash', commands: ['echo d', 'echo e', 'echo f']}]"
    required: true
    default: '[]'

runs:
  using: "composite"
  steps:
    - name: Prepare Environment
      shell: bash
      run: |
        echo "Preparing Environment"
        mkdir -p tmp
        echo "RSCC_TMP_DIR=$(pwd)/tmp" >> $GITHUB_ENV

    - name: Downloading Required Files
      shell: bash
      run: |
        echo "Downloading Required Files"
        mkdir -p /tmp
        curl -sSL https://github.com/gremlinflat/parallel-shell-actions/raw/b0f8e71b28d3760d28f70b92f749cbaa164351d2/static/parallel-shell-executor-v1 -o ${{ env.RSCC_TMP_DIR }}/parallel-shell-executor

    - name: Prepare commands
      shell: bash
      run: |
        echo '${{ inputs.commands }}' > ${{ env.RSCC_TMP_DIR }}/commands.json
  
    - name: Running commands...
      shell: bash
      run: |
        echo "Running commands..."
        cat ${{ env.RSCC_TMP_DIR }}/commands.json
        chmod +x ${{ env.RSCC_TMP_DIR }}/parallel-shell-executor
        ${{ env.RSCC_TMP_DIR }}/parallel-shell-executor -i ${{ env.RSCC_TMP_DIR }}/commands.json

    - name: Cleanup
      shell: bash
      if: always()
      run: |
        echo "Removing temporary files.."
        rm -rf ${{ env.RSCC_TMP_DIR }}
        
        